package com.google.android.gms.internal.mlkit_vision_common;

import com.google.firebase.encoders.config.Configurator;
import com.google.firebase.encoders.config.EncoderConfig;
/* loaded from: classes2.dex */
public final class zzfo implements Configurator {
    public static final Configurator zza = new zzfo();

    private zzfo() {
    }

    @Override // com.google.firebase.encoders.config.Configurator
    public final void configure(EncoderConfig encoderConfig) {
        encoderConfig.registerEncoder(zzhc.class, zzdr.f6524a);
        encoderConfig.registerEncoder(zzin.class, zzfg.f6565a);
        encoderConfig.registerEncoder(zzhd.class, zzds.f6525a);
        encoderConfig.registerEncoder(zzhg.class, zzdu.f6527a);
        encoderConfig.registerEncoder(zzhe.class, zzdt.f6526a);
        encoderConfig.registerEncoder(zzhf.class, zzdv.f6528a);
        encoderConfig.registerEncoder(zzgi.class, zzda.f6507a);
        encoderConfig.registerEncoder(zzgh.class, zzcz.f6506a);
        encoderConfig.registerEncoder(zzgq.class, zzdk.f6517a);
        encoderConfig.registerEncoder(zzij.class, zzfa.f6559a);
        encoderConfig.registerEncoder(zzgg.class, zzcy.f6505a);
        encoderConfig.registerEncoder(zzgf.class, zzcx.f6504a);
        encoderConfig.registerEncoder(zzhm.class, zzed.f6536a);
        encoderConfig.registerEncoder(zzjf.class, zzdg.f6513a);
        encoderConfig.registerEncoder(zzgo.class, zzdi.f6515a);
        encoderConfig.registerEncoder(zzgm.class, zzdf.f6512a);
        encoderConfig.registerEncoder(zzhn.class, zzee.f6537a);
        encoderConfig.registerEncoder(zzig.class, zzex.f6556a);
        encoderConfig.registerEncoder(zzih.class, zzey.f6557a);
        encoderConfig.registerEncoder(zzhk.class, zzeb.f6534a);
        encoderConfig.registerEncoder(zzje.class, zzch.f6488a);
        encoderConfig.registerEncoder(zzhl.class, zzec.f6535a);
        encoderConfig.registerEncoder(zzho.class, zzef.f6538a);
        encoderConfig.registerEncoder(zzhr.class, zzei.f6541a);
        encoderConfig.registerEncoder(zzhq.class, zzeh.f6540a);
        encoderConfig.registerEncoder(zzhp.class, zzeg.f6539a);
        encoderConfig.registerEncoder(zzhw.class, zzen.f6546a);
        encoderConfig.registerEncoder(zzhx.class, zzeo.f6547a);
        encoderConfig.registerEncoder(zzhz.class, zzeq.f6549a);
        encoderConfig.registerEncoder(zzhy.class, zzep.f6548a);
        encoderConfig.registerEncoder(zzhj.class, zzea.f6533a);
        encoderConfig.registerEncoder(zzia.class, zzer.f6550a);
        encoderConfig.registerEncoder(zzib.class, zzes.f6551a);
        encoderConfig.registerEncoder(zzic.class, zzet.f6552a);
        encoderConfig.registerEncoder(zzid.class, zzeu.f6553a);
        encoderConfig.registerEncoder(zzif.class, zzev.f6554a);
        encoderConfig.registerEncoder(zzie.class, zzew.f6555a);
        encoderConfig.registerEncoder(zzhv.class, zzej.f6542a);
        encoderConfig.registerEncoder(zzgx.class, zzdp.f6522a);
        encoderConfig.registerEncoder(zzht.class, zzel.f6544a);
        encoderConfig.registerEncoder(zzhs.class, zzek.f6543a);
        encoderConfig.registerEncoder(zzhu.class, zzem.f6545a);
        encoderConfig.registerEncoder(zzii.class, zzez.f6558a);
        encoderConfig.registerEncoder(zzir.class, zzfk.f6569a);
        encoderConfig.registerEncoder(zzfu.class, zzcm.f6493a);
        encoderConfig.registerEncoder(zzfs.class, zzck.f6491a);
        encoderConfig.registerEncoder(zzfr.class, zzcj.f6490a);
        encoderConfig.registerEncoder(zzft.class, zzcl.f6492a);
        encoderConfig.registerEncoder(zzfw.class, zzco.f6495a);
        encoderConfig.registerEncoder(zzfv.class, zzcn.f6494a);
        encoderConfig.registerEncoder(zzfx.class, zzcp.f6496a);
        encoderConfig.registerEncoder(zzfy.class, zzcq.f6497a);
        encoderConfig.registerEncoder(zzfz.class, zzcr.f6498a);
        encoderConfig.registerEncoder(zzga.class, zzcs.f6499a);
        encoderConfig.registerEncoder(zzgb.class, zzct.f6500a);
        encoderConfig.registerEncoder(zzbh.class, zzcd.f6484a);
        encoderConfig.registerEncoder(zzbj.class, zzcf.f6486a);
        encoderConfig.registerEncoder(zzbi.class, zzce.f6485a);
        encoderConfig.registerEncoder(zzgv.class, zzdn.f6520a);
        encoderConfig.registerEncoder(zzgj.class, zzdb.f6508a);
        encoderConfig.registerEncoder(zzaq.class, zzbl.f6466a);
        encoderConfig.registerEncoder(zzap.class, zzbm.f6467a);
        encoderConfig.registerEncoder(zzgk.class, zzdd.f6510a);
        encoderConfig.registerEncoder(zzas.class, zzbn.f6468a);
        encoderConfig.registerEncoder(zzar.class, zzbo.f6469a);
        encoderConfig.registerEncoder(zzaw.class, zzbr.f6472a);
        encoderConfig.registerEncoder(zzav.class, zzbs.f6473a);
        encoderConfig.registerEncoder(zzau.class, zzbp.f6470a);
        encoderConfig.registerEncoder(zzat.class, zzbq.f6471a);
        encoderConfig.registerEncoder(zzay.class, zzbt.f6474a);
        encoderConfig.registerEncoder(zzax.class, zzbu.f6475a);
        encoderConfig.registerEncoder(zzba.class, zzbv.f6476a);
        encoderConfig.registerEncoder(zzaz.class, zzbw.f6477a);
        encoderConfig.registerEncoder(zzbg.class, zzcb.f6482a);
        encoderConfig.registerEncoder(zzbf.class, zzcc.f6483a);
        encoderConfig.registerEncoder(zzbc.class, zzbx.f6478a);
        encoderConfig.registerEncoder(zzbb.class, zzby.f6479a);
        encoderConfig.registerEncoder(zzbe.class, zzbz.f6480a);
        encoderConfig.registerEncoder(zzbd.class, zzca.f6481a);
        encoderConfig.registerEncoder(zziz.class, zzfd.f6562a);
        encoderConfig.registerEncoder(zzis.class, zzdc.f6509a);
        encoderConfig.registerEncoder(zziw.class, zzdz.f6532a);
        encoderConfig.registerEncoder(zziv.class, zzdy.f6531a);
        encoderConfig.registerEncoder(zzit.class, zzdh.f6514a);
        encoderConfig.registerEncoder(zziy.class, zzfc.f6561a);
        encoderConfig.registerEncoder(zzix.class, zzfb.f6560a);
        encoderConfig.registerEncoder(zzja.class, zzfe.f6563a);
        encoderConfig.registerEncoder(zziu.class, zzdl.f6518a);
        encoderConfig.registerEncoder(zzjd.class, zzfm.f6571a);
        encoderConfig.registerEncoder(zzjc.class, zzfn.f6572a);
        encoderConfig.registerEncoder(zzjb.class, zzfl.f6570a);
        encoderConfig.registerEncoder(zzik.class, zzff.f6564a);
        encoderConfig.registerEncoder(zzgu.class, zzdm.f6519a);
        encoderConfig.registerEncoder(zzgy.class, zzdq.f6523a);
        encoderConfig.registerEncoder(zzfq.class, zzci.f6489a);
        encoderConfig.registerEncoder(zzgp.class, zzdj.f6516a);
        encoderConfig.registerEncoder(zzgw.class, zzdo.f6521a);
        encoderConfig.registerEncoder(zzgl.class, zzde.f6511a);
        encoderConfig.registerEncoder(zzhi.class, zzdx.f6530a);
        encoderConfig.registerEncoder(zzhh.class, zzdw.f6529a);
        encoderConfig.registerEncoder(zzao.class, zzbk.f6465a);
        encoderConfig.registerEncoder(zzio.class, zzfh.f6566a);
        encoderConfig.registerEncoder(zziq.class, zzfj.f6568a);
        encoderConfig.registerEncoder(zzip.class, zzfi.f6567a);
        encoderConfig.registerEncoder(zzfp.class, zzcg.f6487a);
        encoderConfig.registerEncoder(zzge.class, zzcw.f6503a);
        encoderConfig.registerEncoder(zzgd.class, zzcv.f6502a);
        encoderConfig.registerEncoder(zzgc.class, zzcu.f6501a);
    }
}
