package com.google.android.gms.internal.mlkit_common;

import com.google.firebase.encoders.config.Configurator;
import com.google.firebase.encoders.config.EncoderConfig;
/* loaded from: classes.dex */
public final class zzgp implements Configurator {
    public static final Configurator zza = new zzgp();

    private zzgp() {
    }

    @Override // com.google.firebase.encoders.config.Configurator
    public final void configure(EncoderConfig encoderConfig) {
        encoderConfig.registerEncoder(zzih.class, zzes.f6189a);
        encoderConfig.registerEncoder(zzkb.class, zzgh.f6230a);
        encoderConfig.registerEncoder(zzil.class, zzet.f6190a);
        encoderConfig.registerEncoder(zziu.class, zzev.f6192a);
        encoderConfig.registerEncoder(zziq.class, zzeu.f6191a);
        encoderConfig.registerEncoder(zzis.class, zzew.f6193a);
        encoderConfig.registerEncoder(zzhj.class, zzeb.f6172a);
        encoderConfig.registerEncoder(zzhi.class, zzea.f6171a);
        encoderConfig.registerEncoder(zzhs.class, zzel.f6182a);
        encoderConfig.registerEncoder(zzjx.class, zzgb.f6224a);
        encoderConfig.registerEncoder(zzhh.class, zzdz.f6170a);
        encoderConfig.registerEncoder(zzhg.class, zzdy.f6169a);
        encoderConfig.registerEncoder(zzja.class, zzfe.f6201a);
        encoderConfig.registerEncoder(zzkt.class, zzeh.f6178a);
        encoderConfig.registerEncoder(zzhq.class, zzej.f6180a);
        encoderConfig.registerEncoder(zzhp.class, zzeg.f6177a);
        encoderConfig.registerEncoder(zzjb.class, zzff.f6202a);
        encoderConfig.registerEncoder(zzju.class, zzfy.f6221a);
        encoderConfig.registerEncoder(zzjv.class, zzfz.f6222a);
        encoderConfig.registerEncoder(zziy.class, zzfc.f6199a);
        encoderConfig.registerEncoder(zzks.class, zzdi.f6153a);
        encoderConfig.registerEncoder(zziz.class, zzfd.f6200a);
        encoderConfig.registerEncoder(zzjc.class, zzfg.f6203a);
        encoderConfig.registerEncoder(zzjf.class, zzfj.f6206a);
        encoderConfig.registerEncoder(zzje.class, zzfi.f6205a);
        encoderConfig.registerEncoder(zzjd.class, zzfh.f6204a);
        encoderConfig.registerEncoder(zzjk.class, zzfo.f6211a);
        encoderConfig.registerEncoder(zzjl.class, zzfp.f6212a);
        encoderConfig.registerEncoder(zzjn.class, zzfr.f6214a);
        encoderConfig.registerEncoder(zzjm.class, zzfq.f6213a);
        encoderConfig.registerEncoder(zzix.class, zzfb.f6198a);
        encoderConfig.registerEncoder(zzjo.class, zzfs.f6215a);
        encoderConfig.registerEncoder(zzjp.class, zzft.f6216a);
        encoderConfig.registerEncoder(zzjq.class, zzfu.f6217a);
        encoderConfig.registerEncoder(zzjr.class, zzfv.f6218a);
        encoderConfig.registerEncoder(zzjt.class, zzfw.f6219a);
        encoderConfig.registerEncoder(zzjs.class, zzfx.f6220a);
        encoderConfig.registerEncoder(zzjj.class, zzfk.f6207a);
        encoderConfig.registerEncoder(zzhy.class, zzeq.f6187a);
        encoderConfig.registerEncoder(zzjh.class, zzfm.f6209a);
        encoderConfig.registerEncoder(zzjg.class, zzfl.f6208a);
        encoderConfig.registerEncoder(zzji.class, zzfn.f6210a);
        encoderConfig.registerEncoder(zzjw.class, zzga.f6223a);
        encoderConfig.registerEncoder(zzkf.class, zzgl.f6234a);
        encoderConfig.registerEncoder(zzgv.class, zzdn.f6158a);
        encoderConfig.registerEncoder(zzgt.class, zzdl.f6156a);
        encoderConfig.registerEncoder(zzgs.class, zzdk.f6155a);
        encoderConfig.registerEncoder(zzgu.class, zzdm.f6157a);
        encoderConfig.registerEncoder(zzgx.class, zzdp.f6160a);
        encoderConfig.registerEncoder(zzgw.class, zzdo.f6159a);
        encoderConfig.registerEncoder(zzgy.class, zzdq.f6161a);
        encoderConfig.registerEncoder(zzgz.class, zzdr.f6162a);
        encoderConfig.registerEncoder(zzha.class, zzds.f6163a);
        encoderConfig.registerEncoder(zzhb.class, zzdt.f6164a);
        encoderConfig.registerEncoder(zzhc.class, zzdu.f6165a);
        encoderConfig.registerEncoder(zzci.class, zzde.f6149a);
        encoderConfig.registerEncoder(zzck.class, zzdg.f6151a);
        encoderConfig.registerEncoder(zzcj.class, zzdf.f6150a);
        encoderConfig.registerEncoder(zzhw.class, zzeo.f6185a);
        encoderConfig.registerEncoder(zzhm.class, zzec.f6173a);
        encoderConfig.registerEncoder(zzbr.class, zzcm.f6131a);
        encoderConfig.registerEncoder(zzbq.class, zzcn.f6132a);
        encoderConfig.registerEncoder(zzhn.class, zzee.f6175a);
        encoderConfig.registerEncoder(zzbt.class, zzco.f6133a);
        encoderConfig.registerEncoder(zzbs.class, zzcp.f6134a);
        encoderConfig.registerEncoder(zzbx.class, zzcs.f6137a);
        encoderConfig.registerEncoder(zzbw.class, zzct.f6138a);
        encoderConfig.registerEncoder(zzbv.class, zzcq.f6135a);
        encoderConfig.registerEncoder(zzbu.class, zzcr.f6136a);
        encoderConfig.registerEncoder(zzbz.class, zzcu.f6139a);
        encoderConfig.registerEncoder(zzby.class, zzcv.f6140a);
        encoderConfig.registerEncoder(zzcb.class, zzcw.f6141a);
        encoderConfig.registerEncoder(zzca.class, zzcx.f6142a);
        encoderConfig.registerEncoder(zzch.class, zzdc.f6147a);
        encoderConfig.registerEncoder(zzcg.class, zzdd.f6148a);
        encoderConfig.registerEncoder(zzcd.class, zzcy.f6143a);
        encoderConfig.registerEncoder(zzcc.class, zzcz.f6144a);
        encoderConfig.registerEncoder(zzcf.class, zzda.f6145a);
        encoderConfig.registerEncoder(zzce.class, zzdb.f6146a);
        encoderConfig.registerEncoder(zzkn.class, zzge.f6227a);
        encoderConfig.registerEncoder(zzkg.class, zzed.f6174a);
        encoderConfig.registerEncoder(zzkk.class, zzfa.f6197a);
        encoderConfig.registerEncoder(zzkj.class, zzez.f6196a);
        encoderConfig.registerEncoder(zzkh.class, zzei.f6179a);
        encoderConfig.registerEncoder(zzkm.class, zzgd.f6226a);
        encoderConfig.registerEncoder(zzkl.class, zzgc.f6225a);
        encoderConfig.registerEncoder(zzko.class, zzgf.f6228a);
        encoderConfig.registerEncoder(zzki.class, zzem.f6183a);
        encoderConfig.registerEncoder(zzkr.class, zzgn.f6236a);
        encoderConfig.registerEncoder(zzkq.class, zzgo.f6237a);
        encoderConfig.registerEncoder(zzkp.class, zzgm.f6235a);
        encoderConfig.registerEncoder(zzjy.class, zzgg.f6229a);
        encoderConfig.registerEncoder(zzht.class, zzen.f6184a);
        encoderConfig.registerEncoder(zzic.class, zzer.f6188a);
        encoderConfig.registerEncoder(zzgr.class, zzdj.f6154a);
        encoderConfig.registerEncoder(zzhr.class, zzek.f6181a);
        encoderConfig.registerEncoder(zzhx.class, zzep.f6186a);
        encoderConfig.registerEncoder(zzho.class, zzef.f6176a);
        encoderConfig.registerEncoder(zziw.class, zzey.f6195a);
        encoderConfig.registerEncoder(zziv.class, zzex.f6194a);
        encoderConfig.registerEncoder(zzbp.class, zzcl.f6130a);
        encoderConfig.registerEncoder(zzkc.class, zzgi.f6231a);
        encoderConfig.registerEncoder(zzke.class, zzgk.f6233a);
        encoderConfig.registerEncoder(zzkd.class, zzgj.f6232a);
        encoderConfig.registerEncoder(zzgq.class, zzdh.f6152a);
        encoderConfig.registerEncoder(zzhf.class, zzdx.f6168a);
        encoderConfig.registerEncoder(zzhe.class, zzdw.f6167a);
        encoderConfig.registerEncoder(zzhd.class, zzdv.f6166a);
    }
}
